### ISSUE TITLE
Compatibility to 0.5.0

### ISSUE THREAD

**Issue by ChrisWesterfield** [codemancode/errbit_jira_plugin#1]
Hi,

is it possible that you can fix the issues with errbit 0.5?
First of all the app can't start, but that can be fixed really easy.
add the following code to errbit_jira_plugin/issue_tracker.rb

```
def self.icons
  @icons ||= {
    create: [
      'image/png', ErrbitJiraPlugin.read_static_file('jira_create.png')
    ],
    goto: [
      'image/png', ErrbitJiraPlugin.read_static_file('jira_goto.png'),
    ],
    inactive: [
      'image/png', ErrbitJiraPlugin.read_static_file('jira_inactive.png'),
    ]
  }
end
```

then add the method

  def self.read_static_file(file)
    File.read(File.join(self.root, 'static', file))
  end

to errbit_jira_plugin.rb
You need to add 3 Icons

Then the App can start without any issues.
 My Remaining Problem is, that everytim I want to add Jira Issue tracking I get the following error:

[PROJECT_ROOT]/vendor/bundle/ruby/2.1.0/gems/errbit_jira_plugin-0.2.0/lib/errbit_jira_plugin/issue_tracker.rb:77→ block in errors
[PROJECT_ROOT]/vendor/bundle/ruby/2.1.0/gems/errbit_jira_plugin-0.2.0/lib/errbit_jira_plugin/issue_tracker.rb:77→ each
[PROJECT_ROOT]/vendor/bundle/ruby/2.1.0/gems/errbit_jira_plugin-0.2.0/lib/errbit_jira_plugin/issue_tracker.rb:77→ detect
[PROJECT_ROOT]/vendor/bundle/ruby/2.1.0/gems/errbit_jira_plugin-0.2.0/lib/errbit_jira_plugin/issue_tracker.rb:77→ errors

(Github: https://github.com/errbit/errbit/blob/master/app/models/issue_tracker.rb#L30)

Parameters Submited:
{
  "_method" => "patch",
  "action" => "update",
  "app" => {
    "asset_host" => nil,
    "bitbucket_repo" => nil,
    "current_app_version" => nil,
    "github_repo" => nil,
    "issue_tracker_attributes" => {
      "id" => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "options" => {
        "base_url" => "https://jira.xxxxxxxxxxx.de",
        "context_path" => "/",
        "issue_priority" => "Normal",
        "password" => "[FILTERED]",
        "project_id" => "PROJECT",
        "username" => "john.doe"
      },
      "type_tracker" => "jira"
    },
    "name" => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "notification_service_attributes" => {
      "id" => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "type" => "NotificationService"
    },
    "notify_all_users" => "0",
    "notify_on_deploys" => "0",
    "notify_on_errs" => "1",
    "repository_branch" => nil,
    "resolve_errs_on_deploy" => "0"
  },
  "authenticity_token" => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "controller" => "apps",
  "id" => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "utf8" => "✓"
}

Please help

**Comment by stevecrozz** [comment]
@ChrisWesterfield: If the problem is the same as the one you raised on errbit, then this needs a bit more work. Here's an example of a plugin that works using the new plugin interface:
https://github.com/brandedcrate/errbit_pivotal_plugin/blob/master/lib/errbit_pivotal_plugin/issue_tracker.rb

**Comment by ChrisWesterfield** [comment]
Well I'm no developer in ruby on railes.
Just found the issue and a small work around, but I don't really understand the core problem that lies deeper then finding the missing method ^^.
Just wanted to report with as much details as possible

**Comment by stevecrozz** [comment]
No problem. Thanks for reporting this.

**Comment by emgiezet** [comment]
+1 ;)

**Comment by veverkap** [comment]
I'd be happy to help get this updated, but need to know where to start.

What needs to be done?

**Comment by mtmcfarl** [comment]
Thanks for alerting me to this.  I have updated the plugin with the new format that I believe will solve the issues you encountered.

**Comment by ChrisWesterfield** [comment]
Hi,
just updated the Plugin, but no I get new errors.
I attached some screenshots:

![screenshot 2016-04-20 11 29 47](https://cloud.githubusercontent.com/assets/4547775/14669954/6e629baa-06eb-11e6-9bcb-124a0628aed8.png)
![screenshot 2016-04-20 11 29 58](https://cloud.githubusercontent.com/assets/4547775/14669955/6e62b59a-06eb-11e6-81f5-d9994d9f9281.png)

**Comment by ChrisWesterfield** [comment]
Do you need more Informations?

**Comment by mtmcfarl** [comment]
I'll take a closer look this evening. 

Thanks.
